VERILOG_SOURCES = sync_adder.v
SIM=icarus
TOPLEVEL_LANG=verilog
COCOTB_REDUCED_LOG_FMT=1
SIM_BUILD = out
#COMPILE_ARGS =

# TOPLEVEL is the name of the toplevel module in your VHDL file:
TOPLEVEL=adder

# MODULE is the name of the Python test file:
MODULE=tb

#included for cocotb
include $(shell cocotb-config --makefiles)/Makefile.sim